{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: {{ include "istio-job-cleaner.serviceAccountName" . }}-crb
  labels:
    {{- include "istio-job-cleaner.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "istio-job-cleaner.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "istio-job-cleaner.serviceAccountName" . }}-cr
  apiGroup: rbac.authorization.k8s.io
{{- end }}